add gpg content
githubtraining/training-manual pull request #253
Opened 2020-08-28 17:35 UTC by beardofedu

This pull request adds GPG content to the training manual as identified in #240.

2020-08-30 21:00 UTC, haothang commented
240

2020-08-31 14:39 UTC, rwnfoo submitted a review, later dismissed

2020-09-01 11:43 UTC, ppremk commented on docs/24_commit_sig_verification.md
> +Signed commits can be created by implementing GPG or S/MIME signature that is attached to every commit that you make. Once you have integrated GPG or S/MIME on your machine and account, commits you c
```suggestion
Signed commits can be created by implementing GPG or S/MIME signature that is attached to every commit that you make on your local machine (downstream repository). Once you have integrated GPG or S/MIME on your machine and account, commits you create locally and push to the upstream will appear like this in the GitHub UI:
```

2020-09-01 11:46 UTC, ppremk commented on docs/24_commit_sig_verification.md
> +An unverified commit will not display the "Verified" tag in the GitHub interface.
```suggestion
An unsigned commit on the local downstream repo will not display the "Verified" tag in the GitHub interface. Any commits made directly on the GitHub interface will automatically include the "Verified" tag.
```

2020-09-01 11:57 UTC, ppremk commented on docs/24_commit_sig_verification.md
> +1. Create a pull request and in the **Commits** tab you will see the **Verified** tag next to your commit.
```suggestion
1. Create a pull request and in the **Commits** tab you will see the **Verified** tag next to your commit.


> Note: If you've enforced branch protections in your repository, you can set up required commit signing. When you enable required commit signing on a branch, contributors can only push local commits to the branch if they are signed and verified. Contributors can merge signed and verified commits using the GitHub Enterprise web interface. For more information, see [Configuring protected branches.](https://docs.github.com/en/enterprise/2.15/user/articles/configuring-protected-branches)
```

2020-09-01 11:58 UTC, ppremk requested changes
Added some minor tweaks @beardofedu

2020-09-03 22:47 UTC, parkerbxyz approved these changes

2020-09-04 12:35 UTC, beardofedu commented
@ppremk can you re-review this since @parkerbxyz implemented your changes? Once you are done, just merge it 👍

2020-09-04 13:56 UTC, ppremk approved these changes

2020-09-04 13:57 UTC, merged