Refactor new-virtual → create-initial-repo
githubtraining/training-manual pull request #342
Opened 2021-11-10 06:37 UTC by parkerbxyz

Replaces script/new-virtual and script/create-repo with script/create-initial-repo.

Closes #341 #321 #334 #285 #218 #214

2021-11-10 13:46 UTC, AAugustine commented
Tested with a class 19 people. I tried to create github-games repos for the participants.
The script successfully created repos and pull requests for 9 people in the class.
But then the creation of Pull Requests began to fail and returned an error `http: warning: HTTP 403 Forbidden` for each attempt.  I does manage to create repos for all 19 people but fails at creating the pull requests.

Maybe we are hitting a rate limit and could possibly throttle the http requests if that's the case.

I am including a file that contains the output from the command. There was nothing in the `log.out` file.
[refactor-new-virtual-output.txt](https://github.com/githubtraining/training-manual/files/7513085/refactor-new-virtual-output.txt)
e.

2021-11-10 13:58 UTC, AAugustine reviewed
I ran into some issues when testing the creating of github-games repos for a class of 19. I left more information in the PR conversation.

2021-11-10 14:14 UTC, amyschoen commented
That does appear to be a rate limit @AAugustine.  They do result in a 403, and have two formats.  This is the message for hitting an unauthenticated rate limit:

`API rate limit exceeded for x.x.x.x. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)`

Here's the one for hitting the authenticated rate limit:

`API rate limit exceeded for user ID #.`

2021-11-10 16:26 UTC, parkerbxyz commented
[Dealing with secondary rate limits](https://docs.github.com/en/rest/guides/best-practices-for-integrators#dealing-with-secondary-rate-limits).

> If you're making a large number of `POST`, `PATCH`, `PUT`, or `DELETE` requests for a single user or client ID, wait at least one second between each request.

This should be easy enough to implement.

2021-11-10 17:30 UTC, parkerbxyz commented
I added a one second wait before creating issues and PRs via 4ce4461. Let me know if this fixes the issue for you, @AAugustine. 🙂

2021-11-10 22:19 UTC, AAugustine commented
Preliminary testing with 8 participants worked well.  I'm going to collect a group of 10-15 people internally to test a larger group since I won't have another large class for about 2 weeks.

2021-11-10 23:04 UTC, amyschoen requested changes
This is a no-go for me.

```
Updating contents of README.md... Done.
Updating contents of _config.yml... Done.
usage: http [--json] [--form] [--multipart] [--boundary BOUNDARY] [--compress] [--pretty {all,colors,format,none}] [--style STYLE] [--unsorted]
            [--sorted] [--format-options FORMAT_OPTIONS] [--print WHAT] [--headers] [--body] [--verbose] [--all] [--history-print WHAT] [--stream]
            [--output FILE] [--download] [--continue] [--quiet] [--session SESSION_NAME_OR_PATH | --session-read-only SESSION_NAME_OR_PATH]
            [--auth USER[:PASS]] [--auth-type {basic,digest}] [--ignore-netrc] [--offline] [--proxy PROTOCOL:PROXY_URL] [--follow]
            [--max-redirects MAX_REDIRECTS] [--max-headers MAX_HEADERS] [--timeout SECONDS] [--check-status] [--path-as-is] [--chunked]
            [--verify VERIFY] [--ssl {ssl2.3,tls1,tls1.1,tls1.2}] [--ciphers CIPHERS] [--cert CERT] [--cert-key CERT_KEY] [--ignore-stdin] [--help]
            [--version] [--traceback] [--default-scheme DEFAULT_SCHEME] [--debug]
            [METHOD] URL [REQUEST_ITEM ...]
http: error: unrecognized arguments: --raw
```

Marking it as `Request changes` so it doesn't get merged before I have time to investigate further tomorrow.

2021-11-10 23:28 UTC, parkerbxyz commented on script/create-initial-repo
> +  echo "What are the class dates? (e.g. May 4 – 7, 2021)"
May the 4th be with you 😉

2021-11-10 23:31 UTC, parkerbxyz commented
> This is a no-go for me.

@amyschoen `--raw` was added to HTTPie in [2.5.0](https://github.com/httpie/httpie/releases/tag/2.5.0). Updating should fix this for you. 

If you use Homebrew, this should do the trick:

```
brew upgrade httpie
```

2021-11-11 00:46 UTC, amyschoen commented
Thanks @parkerbxyz. I figured it was something like that. I’ll update and test tomorrow once I’m back in front of a computer.

2021-11-12 20:01 UTC, amyschoen commented
Haven't gotten a successful class repo created yet.  Still running into issues, but the upgrade fixed the error over raw.

```
Updating contents of README.md... Done.
Updating contents of _config.yml... Done.

http: warning: HTTP 415 Unsupported Media Type

Error! Failed to update branch protection rules.
Creating issue: Add collaborators to this repo... Done.
Creating project: Caption Contest... 
http: warning: HTTP 415 Unsupported Media Type

Done.
Creating project column: To do... 
http: warning: HTTP 404 Not Found

Done.
Creating project column: In progress... 
http: warning: HTTP 404 Not Found

Done.
Creating project column: Done... 
http: warning: HTTP 404 Not Found

Done.
Creating project card: ... 
http: warning: HTTP 404 Not Found


http: warning: HTTP 415 Unsupported Media Type
```

@parkerbxyz, were there any changes to the template repos that I need to bring down to my local versions in GHES?

2021-11-12 20:08 UTC, amyschoen commented
Digging in, I'm seeing this:

`--body "Let's see who can create the best captions for our collection of memes."`

Did we change back to memes from Octocats?

2021-11-12 20:11 UTC, parkerbxyz commented
> ```
> Error! Failed to update branch protection rules.
> ```

I wonder if the endpoint being used is different on GHES. I’ve only tested on github.com.

> ```
> Creating project: Caption Contest... 
> http: warning: HTTP 415 Unsupported Media Type
> 
> Done.
>
> Creating project column: To do... 
> http: warning: HTTP 404 Not Found
> 
> Done.
> Creating project column: In progress... 
> http: warning: HTTP 404 Not Found
> 
> Done.
> Creating project column: Done... 
> http: warning: HTTP 404 Not Found
> 
> Done.
> ```

If the project fails to be created, the other project-related operations (creating columns and cards) will also fail. We should handle this more gracefully and only try to create columns and cards if the project is successfully created. 

It also looks like the error handling on these functions need a little work. It shouldn’t say “Done” if it failed.

2021-11-12 20:28 UTC, amyschoen commented
>  I wonder if the endpoint being used is different on GHES. I’ve only tested on github.com.

I'm starting to suspect it's something like that @parkerbxyz.  I'm troubleshooting and inserting a bunch of random echos to get an idea of where it's going wrong.  Something has changed or is subtly different with the new way of doing things since I had zero issues with using the older version of the scripts when I taught my last class.

2021-11-12 22:02 UTC, amyschoen commented
I think it might be headers.  I'm noticing that branch protection has a header of `Accept: application/vnd.github.loki-preview+json` and projects have a header of `Accept: application/vnd.github.inertia-preview+json`.  I'll bet it's in preview in GHES and not in preview on .com.  Testing my theory by adding back the headers in my local version.

2021-11-12 23:17 UTC, amyschoen commented
Tricky...you added in required reviews which requires a header of `application/vnd.github.luke-cage-preview+json`.  I got past the issue on branch protection.  I'll add it as a review suggestion and then move on to figuring out the necessary headers for the project calls.

2021-11-12 23:18 UTC, amyschoen commented on script/create-initial-repo
> +  }' PUT "$org_repos_endpoint/$initial_repo_name/branches/$default_branch/protection"; then
```suggestion
  }' PUT "$org_repos_endpoint/$initial_repo_name/branches/$default_branch/protection" "Accept:application/vnd.github.luke-cage-preview+json"; then
```

2021-11-12 23:22 UTC, amyschoen commented on script/shared_functions
> +    name="$name" \
```suggestion
    "$TOKEN_OWNER:$TEACHER_PAT" "$projects_endpoint" \
    "Accept:application/vnd.github.inertia-preview+json" \
    name="$name" \
```

2021-11-12 23:28 UTC, amyschoen commented on script/shared_functions
> +    project_id="$project_id" \
```suggestion
    "$TOKEN_OWNER:$TEACHER_PAT" "$project_column_endpoint" \
    "Accept:application/vnd.github.inertia-preview+json" \
    project_id="$project_id" \
```

2021-11-12 23:44 UTC, amyschoen commented
Are you sure project cards are working?  The call you're using doesn't match any of the API documentation on either GHES or .com.

https://docs.github.com/en/enterprise-server@3.2/rest/reference/projects#create-a-project-card
https://docs.github.com/en/rest/reference/projects#create-a-project-card

2021-11-12 23:51 UTC, amyschoen commented on script/shared_functions
> +    project_id="$project_id" \
```suggestion
    "$TOKEN_OWNER:$TEACHER_PAT" "$project_card_endpoint" \
    "Accept:application/vnd.github.inertia-preview+json" \
    project_id="$project_id" \
```

2021-11-12 23:59 UTC, amyschoen commented
Figured it out.  Cards was fine with the header added even though it doesn't match the API documentation.  @parkerbxyz, can you file a bug with whatever team does the API documentation for that.  Enabling pages was what was failing for me.  I figured out the necessary header.  Once I add that suggestion in, I'm done testing for the week.  Only got through creating the initial class repo.  I'll test everything past that next week.

2021-11-13 00:00 UTC, amyschoen commented on script/create-initial-repo
> +  }' POST "$org_repos_endpoint/$initial_repo_name/pages"; then
```suggestion
  }' POST "$org_repos_endpoint/$initial_repo_name/pages" "Accept:application/vnd.github.switcheroo-preview+json"; then
```

2021-11-15 16:20 UTC, chundric reviewed
ok

2021-12-22 20:37 UTC, parkerbxyz commented
> Figured it out. Cards was fine with the header added even though it doesn't match the API documentation. @parkerbxyz, can you file a bug with whatever team does the API documentation for that. Enabling pages was what was failing for me. I figured out the necessary header.

@amyschoen What version of GHES are you on?

2021-12-22 21:03 UTC, parkerbxyz commented
The natural language check is failing because of the following issue: https://github.com/sapegin/textlint-rule-terminology/issues/38.

2022-01-03 15:25 UTC, amyschoen commented
> @amyschoen What version of GHES are you on? Maybe you’re on an older version that still requires the preview header? https://github.blog/changelog/2021-10-14-rest-api-preview-promotions/

Looks like we're running 3.1.14.  Does it work to include the headers or does it break newer versions?

2022-01-07 00:28 UTC, parkerbxyz commented
> Does it work to include the headers or does it break newer versions?

It seems to work fine with the header on github.com. I don’t have a newer version of GHES readily available to test against, but it should handle the headers just fine. They’re just no longer required in the newer versions.

2022-01-07 00:31 UTC, parkerbxyz commented
@amyschoen if you’re good with the changes now that those headers are in there, this PR will auto-merge upon your approving review.

2022-01-07 02:23 UTC, amyschoen commented
That works for me. I’ll pull down the current state of the code when I’m back in front of my computer tomorrow and run some quick tests prior to approving.

2022-01-10 22:41 UTC, amyschoen commented
@parkerbxyz, I got a little delayed.  I blocked an hour off tomorrow to make sure I get this tested and approved.

2022-01-11 00:43 UTC, parkerbxyz commented
No worries. Thanks, @amyschoen!

2022-01-11 19:55 UTC, amyschoen commented on practice-repos/caption-this/issue_1.md
> +You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unatch** button at the top of the page and selecting either the **Participating and @mentions** or *
```suggestion
You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unwatch** button at the top of the page and selecting either the **Participating and @mentions** or **Ignore** option.
```

2022-01-11 19:55 UTC, amyschoen commented on practice-repos/caption-this/issue_1.md
> +You'll start to receive a lot of emails. (❗) You can slow these down immediately by clicking the **Unatch** button at the top of the page and selecting either the **Participating and @mentions** or *
@parkerbxyz, just started testing.  Find a minor typo.

2022-01-11 20:04 UTC, amyschoen commented
@parkerbxyz, it mostly tests fine.  The initial class repo gets created okay.  Making it private works.  I'm able to get collaborators added fine from the commenters on the initial issue.  Conflict repos and GitHub games are working.

Unfortunately, I'm not getting any slides generated in the initial class repo.  I'm investigating now.

2022-01-11 23:43 UTC, amyschoen commented
I commented out the delete.  Looks like the files are successfully created.  Did you mean to have everything prefixed with a 2 instead of sequential numbers like we've used previously?  Names altered to protect our internal user names, but I got 02-Amy.md and 02-Josh.md.  Historically, it would've been one of us with an 02 and one with an 03.

2022-01-12 00:05 UTC, amyschoen commented
Looks like branch protection is the issue.

```
{
  "message": "Could not create file: At least 1 approving review is required by reviewers with write access.",
  "documentation_url": "https://docs.github.com/enterprise/3.1/user/articles/about-protected-branches"
}
```

We need to make sure that `Include administrators` is not checked.  It fixed the numbering issue as well.

2022-01-12 00:07 UTC, amyschoen requested changes
@parkerbxyz, I think we should be good after you accept my last couple suggestions.  The first one is a minor typo.  The one I just added on branch protections is a big one.  It means that no slides would be generated for anyone.

2022-01-12 00:07 UTC, amyschoen commented on script/create-initial-repo
> +    "enforce_admins": true,
```suggestion
    "enforce_admins": false,
```

2022-01-12 00:20 UTC, parkerbxyz commented on script/create-initial-repo
> +    "enforce_admins": true,
Nice catch. Thanks!

2022-01-12 21:26 UTC, amyschoen approved these changes
Everything is running smoothly now.

2022-01-12 21:26 UTC, merged

2022-01-12 21:27 UTC, amyschoen commented
@parkerbxyz, this one's been open for awhile.  Feels good to finally wrap it up.  The new automation is great around the auto merging.

2022-01-12 21:47 UTC, parkerbxyz commented
Woohoo! It’s also nice to get 6 issues closed as a result of merging this. 😎 Thanks for your help testing on GHES, @amyschoen! ✨